/**
 * Seeds demo vendors, products and a demo buyer.
 *
 *   pnpm seed:emu   -> against the local emulators (.env.emulator)
 *   pnpm seed       -> against the hosted project (.env)
 *
 * Runs with the web SDK as each vendor, so security rules are exercised too.
 * Safe to re-run: existing accounts are reused and products are keyed by slug.
 * Product data lives in catalog.json; photos come from seed-images.json
 * (generated by resolve-images.mjs from Wikimedia Commons), with a labelled
 * placeholder for anything unresolved.
 */
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { initializeApp } from 'firebase/app'
import { connectAuthEmulator, createUserWithEmailAndPassword, getAuth, signInWithEmailAndPassword, signOut } from 'firebase/auth'
import { connectFirestoreEmulator, doc, getDoc, getFirestore, serverTimestamp, setDoc, writeBatch } from 'firebase/firestore'

const env = (k: string, fallback = '') => process.env[k] ?? fallback

const app = initializeApp({
  apiKey: env('VITE_FIREBASE_API_KEY', 'demo-key'),
  authDomain: env('VITE_FIREBASE_AUTH_DOMAIN', 'localhost'),
  projectId: env('VITE_FIREBASE_PROJECT_ID', 'window-dev'),
  appId: env('VITE_FIREBASE_APP_ID', 'demo'),
})
const auth = getAuth(app)
const db = getFirestore(app)
if (env('VITE_USE_EMULATOR') === 'true') {
  connectAuthEmulator(auth, 'http://127.0.0.1:9099', { disableWarnings: true })
  connectFirestoreEmulator(db, '127.0.0.1', 8080)
}

export const DEMO_PASSWORD = 'window123'

type Avail = 'in_stock' | 'low' | 'out_of_stock'
interface SeedProduct {
  slug: string
  title: string
  description: string
  price: number | null
  category: string
  query: string[]
  availability?: Avail
}
interface SeedVendor {
  email: string
  owner: string
  name: string
  description: string
  tags: string[]
  website: string | null
  location: { lat: number; lng: number; address: string }
  ownerPhone: string
  products: SeedProduct[]
}

const here = path.dirname(fileURLToPath(import.meta.url))
const { vendors } = JSON.parse(readFileSync(path.join(here, 'catalog.json'), 'utf8')) as { vendors: SeedVendor[] }
const imagesPath = path.join(here, 'seed-images.json')
const images: Record<string, string[]> = existsSync(imagesPath) ? JSON.parse(readFileSync(imagesPath, 'utf8')) : {}

const placeholder = (label: string) =>
  `https://placehold.co/640x854/ede9fe/5518d8/png?text=${encodeURIComponent(label.slice(0, 40))}&font=inter`

function imageUrls(p: SeedProduct): string[] {
  const resolved = images[p.slug] ?? []
  return resolved.length ? resolved : [placeholder(p.title)]
}

async function signInOrCreate(email: string) {
  try {
    return (await signInWithEmailAndPassword(auth, email, DEMO_PASSWORD)).user
  } catch {
    return (await createUserWithEmailAndPassword(auth, email, DEMO_PASSWORD)).user
  }
}

async function seedVendor(v: SeedVendor, vendorIndex: number) {
  const user = await signInOrCreate(v.email)
  const uid = user.uid
  if (!(await getDoc(doc(db, 'users', uid))).exists()) {
    await setDoc(doc(db, 'users', uid), { role: 'vendor', displayName: v.owner, avatarUrl: null, createdAt: serverTimestamp() })
  }
  const storefront = (images[v.products[0]!.slug] ?? [])[0] ?? placeholder(v.name)
  const existingVendor = await getDoc(doc(db, 'vendors', uid))
  await setDoc(
    doc(db, 'vendors', uid),
    {
      ownerUid: uid,
      name: v.name,
      description: v.description,
      logoUrl: null,
      storefrontUrl: storefront,
      website: v.website,
      tags: v.tags,
      location: v.location,
      ownerName: v.owner,
      ownerPhone: v.ownerPhone,
      ownerEmail: v.email,
      phoneVerified: true,
      emailVerified: true,
      // `verified` is immutable under the rules once the doc exists.
      verified: existingVendor.exists() ? (existingVendor.data()!.verified ?? false) : false,
      createdAt: serverTimestamp(),
    },
    { merge: true },
  )
  const batch = writeBatch(db)
  v.products.forEach((p, i) => {
    const id = `${uid.slice(0, 6)}-${p.slug}`
    batch.set(doc(db, 'products', id), {
      vendorId: uid,
      vendorName: v.name,
      title: p.title,
      description: p.description,
      price: p.price,
      currency: 'INR',
      category: p.category,
      imageUrls: imageUrls(p),
      availability: p.availability ?? 'in_stock',
      // Stagger createdAt so the feed interleaves vendors.
      createdAt: new Date(Date.now() - (i * 4 + vendorIndex) * 3_600_000),
      updatedAt: serverTimestamp(),
    })
  })
  await batch.commit()
  console.log(`✔ ${v.name} (${v.email}): ${v.products.length} products`)
  await signOut(auth)
}

async function seedBuyer() {
  const user = await signInOrCreate('buyer@window.demo')
  if (!(await getDoc(doc(db, 'users', user.uid))).exists()) {
    await setDoc(doc(db, 'users', user.uid), { role: 'buyer', displayName: 'Demo Shopper', avatarUrl: null, createdAt: serverTimestamp() })
  }
  console.log('✔ buyer@window.demo')
  await signOut(auth)
}

async function main() {
  console.log(`Seeding project ${env('VITE_FIREBASE_PROJECT_ID')} ${env('VITE_USE_EMULATOR') === 'true' ? '(emulator)' : '(hosted)'}`)
  for (let i = 0; i < vendors.length; i++) await seedVendor(vendors[i]!, i)
  await seedBuyer()
  console.log(`\nDemo accounts (password: ${DEMO_PASSWORD}):`)
  for (const v of vendors) console.log(`  vendor  ${v.email}`)
  console.log('  buyer   buyer@window.demo')
  process.exit(0)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
